# Image-Comparator Dockerfile
FROM ubuntu

# These are essential
RUN apt update -y;
RUN apt install -y python3.8;
RUN apt-get install -y python3-pip;
RUN apt-get install -y vim;
RUN apt-get install -y ruby;
RUN gem install couchrest;
RUN gem install pry;
RUN apt-get install curl -y;

ENTRYPOINT ["bash"]
#CMD ["8080"]

