# Image-Comparator Dockerfile
FROM ubuntu
MAINTAINER bbearce <bbearce@mgh.harvard.edu>

# These are essential
RUN apt update -y;
RUN apt install -y python3.8;
RUN apt-get -y install python3-pip
RUN apt-get install -y vim;

ENTRYPOINT ["bash"]
#CMD ["8080"]

